#!/bin/bash
#

# Abbort script on command failure
set -e
. helper-setup-buildroot

VERSION=1.1
BUILDROOT_MANIFEST="fs-release-manifest.xml"

RELEASE=$(parse_xml_value "release" "version" "${BUILDROOT_MANIFEST}")
DOCKER_VERSION=$(parse_xml_value "docker" "version" "${BUILDROOT_MANIFEST}")

# F&S github home
FUS_GITHUB_HOME_URL="https://github.com/FSEmbedded"
# env. defines home repository URL
GITHUB_HOME_URL=${GITHUB_HOME_URL:-"${FUS_GITHUB_HOME_URL}"}
# env. defines repository name for releases
RELEASES_REPO_NAME=${RELEASES_REPO_NAME:-"releases-fus"}

BUILDROOT_DOWNLOAD_URL="${GITHUB_HOME_URL}/${RELEASES_REPO_NAME}"
BUILDROOT_BRANCH=${BUILDROOT_BRANCH:-"main"}
WORKDIR=$(pwd)

EXAMPLES_DIR=examples-fus
LINUX_DIR=linux-fus
UBOOT_DIR=u-boot-fus
BUILDROOT_DIR=buildroot-fus

DL_DIR="dl"
UPDATE="false"
DOCKER_CMD="bash"

ARCH=$(parse_xml_value "release" "arch" "${BUILDROOT_MANIFEST}")
MACHINE="${MACHINE:-$ARCH}"
DISTRO="${DISTRO:-wayland}"

LINUX_FUS_BRANCH=$(parse_xml_value "project name=\"linux-fus\"" "upstream" "${BUILDROOT_MANIFEST}")
UBOOT_FUS_BRANCH=$(parse_xml_value "project name=\"u-boot-fus\"" "upstream" "${BUILDROOT_MANIFEST}")

# ----- Parse arguments -------------------------------------------------------

force=0
run=
TARGET=

while [ $# -gt 0 ] ; do
    case "${1,,}" in
    --accept-eula)
        HEADLESS="--headless"
        shift
        ;;
	-r|--release)
	    if [ -z "$2" ] ; then
		echo
		echo "ERROR: Option '$1' needs a path parameter"
		show_usage
	    fi
	    RELEASE="$2"
	    shift 2
	    ;;
	-d|--dl)
	    if [ -z "$2" ] ; then
		echo
		echo "ERROR: Option '$1' needs a path parameter"
		show_usage
	    fi
	    DL_DIR="$2"
	    shift 2
	    ;;
	--docker)
		shift
		while [ $# -gt 0 ] ; do
			case "${1,,}" in
				cmd=*)
					DOCKER_CMD=${1#*=}
					shift
					;;
				params=*)
					DOCKER_PARAMS=${1#*=}
					shift
					;;
				*)
					shift
					;;
			esac
		done
		do_docker
		exit 0
	    ;;
	--build)
		do_build
		exit 0
	    ;;
	--cve-tracker)
		do_cve_tracker
		exit 0
	    ;;
	-h|--help)
	    show_usage
	    ;;
	-f|--force)
	    force="true"
	    shift
	    ;;
	-n|--dry-run)
	    run=:
	    shift
	    ;;
	-u|--update)
	    UPDATE="true"
	    shift
	    ;;
	-v|--version)
	    echo $VERSION
		exit
		;;
	-*)
	    echo
	    echo "ERROR: Unknown option '$1'"
	    show_usage
	    ;;

	*)
	    TARGET="$1"
	    echo "TARGET=$TARGET" > .env
	    shift
	    ;;
    esac
done

if [ -z "$RELEASE" ] ; then
    RELEASE=$(dirname "$0")
fi

echo

if [ -z "$TARGET" ] ; then
    echo "No target directory given; use . to install to current directory"
    show_usage
fi

# OK, let's start. Prepend all delete and installation commands with $run.
# Then they are automatically skipped in case of --dry-run.

if [ "$run" == ":" ] ; then
    echo "*** Dry run -- the following actions would be executed ***"
    echo
fi

# ----- Remove existing files and directories ---------------------------------

# Check for main target directory

if [ -e "$TARGET" ] && [ "$UPDATE" != "true" ] ; then
	do_delete "$TARGET"
fi

# Check dl directory; package names must not contain blanks
dl_packages=
install_dl_packages=
create_dl_link=1
DL_REL_DIR="dl"
DL_DIR="$TARGET/buildroot-fus/dl"
if [ -z "$DL_DIR" ] ; then
    DL_DIR="$TARGET/$DL_DEF_DIR"
    create_dl_link=0
fi
if [ -d "$DL_REL_DIR" ] ; then
    dl_packages=$(cd "$DL_REL_DIR"; echo *)
fi
if [ -d "$DL_DIR" ] ; then
    for package in $dl_packages ; do
	dlpackage="$DL_DIR/$package"
	if [ -e "$dlpackage" ] ; then
	    # Skip if existing package is identical
	    if cmp -s "$DL_REL_DIR/$package" "$dlpackage" ; then
		continue
	    fi
	    do_delete "$dlpackage"
	fi
	# Add this package
	install_dl_packages="$install_dl_packages $package"
    done
else
    # Add all packages
    install_dl_packages="$dl_packages"
fi

# Stop on problems with existing files
if [ "$stop" == 1 ] ; then
    echo
    echo "*** Move away the file(s) or use option --force (-f) to delete. ***"
    echo
    exit 1;
fi

# ----- Unpack archives and set up environment --------------------------------

echo "Setup release $RELEASE"
echo

# Create target directory if it does not exist yet
if [ ! -d "$TARGET" ] ; then
    do_mkdir "$TARGET"
fi

do_set_git_credentials

$run cd $TARGET

if [ $UPDATE == "true" ] ; then
    do_buildroot_update
else
	do_buildroot_download
fi


$run cd $BUILDROOT_DIR

# Create downloads directory if it does not exist yet
if [ ! -d "$DL_DIR" ] ; then
		do_mkdir "$DL_DIR"
fi

$run cd $WORKDIR

# Copy extra packages from dl, if any
if [ -d "$DL_REL_DIR" ] ; then
    if [ ! -d "$DL_DIR" ] ; then
	do_mkdir "$DL_DIR"
    fi
    for package in $install_dl_packages ; do
	do_copy "$DL_REL_DIR/$package" "$DL_DIR/$package"
    done
fi

echo
